---
- hosts: all
  vars:
    user: "{{ ansible_env.USER }}"
  tasks:
    - name: print var
      debug:
        msg: "User: {{ user }}"

    - name: Create user file
      become_user: "{{ user }}"
      file:
        path: /tmp/my_file_{{ user }}
        state: touch

    - name: Create root file
      become: yes
      file:
        path: /tmp/my_file_root
        state: touch